### ISSUE TITLE
support for other locales

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [Innmind/ServerStatus#1]
$process = new SfProcess('export LC_TIME=\'en_EN.UTF-8\'; '.$command);

helps using this if your macbook is set to other locales than en_EN

**Comment by Baptouuuu** [comment]
I'm not sure to understand, allowing to specify the locale would change the output from which command ?

Can you provide examples of what result you expect ?

**Comment by Baptouuuu** [comment]
Since [version `4.0.0`](https://github.com/Innmind/ServerStatus/releases/tag/4.0.0) the problem no longer exist since the parent environment is not longer forwarded to the inner commands.
